name: travel_app_237
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.3.0
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - images/cmr_flag.jpg
    - images/dla.webp
    - images/ICT_U_logo.jpg
    - images/nsamba.jpg
    - images/pigmee.jpeg
    - images/ynd.jpeg
    - images/foumban_img.jpg
    - images/mount_cmr.jpg
    - images/seme_beach.jpg
    - images/Ntn_museum.jpg
    - images/tagidor.webp
    - images/ekom_nkam.jpg
    - images/mont_nsamba.jpg